networks:
  testing_network:
    driver: bridge
services:
  webserver:
    init: true
    build:
      context: ./server
      target: dev
      args:
        TESTING: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthcheck"]
      interval: 1s
      timeout: 2s
      retries: 3
    ports:
      - 8080
    depends_on:
      migrator:
        condition: service_completed_successfully
    environment:
      PORT: 8080
      DATABASE_URL: postgres://dfuser:testing_postgres_password@postgres:5432/dfmailbox
      TESTING_MODE: true
      HOST: ${DFMC_ADDRESS}
      SECRET_KEY: ${DFMC_PRIVATE_KEY}
    develop:
      watch:
        - action: rebuild
          path: ./server/src
    stop_grace_period: 1s
    restart: no
    networks:
      - testing_network

  migrator:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command:
      - "-path=/migrations/"
      - "-database=postgres://dfuser:testing_postgres_password@postgres:5432/dfmailbox?sslmode=disable"
      - "up"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    restart: no
    networks:
      - testing_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: dfmailbox
      POSTGRES_USER: dfuser
      POSTGRES_PASSWORD: testing_postgres_password
    restart: no
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dfuser -d dfmailbox"]
      interval: 3s
      timeout: 5s
      start_period: 5s
      start_interval: 0.5s
      retries: 5
    networks:
      - testing_network

