services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DFPS_POSTGRES_DB:-dftools}
      POSTGRES_USER: ${DFPS_POSTGRES_USER:-dfuser}
      POSTGRES_PASSWORD: ${DFPS_POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  webserver:
    init: true
    build:
      context: .
      # In .env make TARGET=dev for faster builds at the cost of size
      target: ${TARGET:-prod}
    ports:
      - ${DFPS_PORT:-3000}:${DFPS_PORT:-8080}
    depends_on:
      - postgres
      - redis
    environment:
      PORT: ${DFPS_PORT:-8080}
      DATABASE_URL: postgres://${DFPS_POSTGRES_USER:-dfuser}:${DFPS_POSTGRES_PASSWORD}@postgres:5432/${DFPS_POSTGRES_DB:-dftools}
      REDIS_URL: redis://redis:6379/0
      URL_PATH: ${DFPS_PATH}
      JWT_KEY: ${DFPS_JWT_KEY}
      SECRET_KEY: ${DFPS_SECRET_KEY}
    develop:
      watch:
        - action: rebuild
          path: ./src
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

