services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DFQ_POSTGRES_DB:-dfqueue}
      POSTGRES_USER: ${DFQ_POSTGRES_USER:-dfuser}
      POSTGRES_PASSWORD: ${DFQ_POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  webserver:
    init: true
    build:
      context: ./server
      # In .env make TARGET=dev for faster builds at the cost of size and stopping for some reason
      target: ${TARGET:-prod}
    ports:
      - ${DFQ_PORT:-8080}:${DFQ_INT_PORT:-8080}
    depends_on:
      - migrator
    environment:
      PORT: ${DFQ_INT_PORT:-8080}
      DATABASE_URL: postgres://${DFQ_POSTGRES_USER:-dfuser}:${DFQ_POSTGRES_PASSWORD}@postgres:5432/${DFQ_POSTGRES_DB:-dfqueue}
      HOST: ${DFQ_HOST}
      SECRET_KEY: ${DFQ_SECRET_KEY}
    develop:
      watch:
        - action: rebuild
          path: ./server/src
    stop_grace_period: ${DFQ_DEV_GRACE_PERIOD:-5s}
    restart: unless-stopped

  migrator:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command:
      - "-path=/migrations/"
      - "-database=postgres://${DFQ_POSTGRES_USER:-dfuser}:${DFQ_POSTGRES_PASSWORD}@postgres:5432/${DFQ_POSTGRES_DB:-dfqueue}?sslmode=disable"
      - "up"
    depends_on:
      - postgres
    restart: "no"

volumes:
  postgres_data:

