services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DFM_POSTGRES_DB:-dfmailbox}
      POSTGRES_USER: ${DFM_POSTGRES_USER:-dfuser}
      POSTGRES_PASSWORD: ${DFM_POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  webserver:
    init: true
    build:
      context: ./server
      # In .env make TARGET=dev for faster builds at the cost of size and stopping for some reason
      target: ${TARGET:-prod}
    ports:
      - ${DFM_PORT:-8080}:${DFM_INT_PORT:-8080}
    depends_on:
      migrator:
        condition: service_completed_successfully
    environment:
      PORT: ${DFM_INT_PORT:-8080}
      DATABASE_URL: postgres://${DFM_POSTGRES_USER:-dfuser}:${DFM_POSTGRES_PASSWORD}@postgres:5432/${DFM_POSTGRES_DB:-dfmailbox}
      HOST: ${DFM_HOST}
      SECRET_KEY: ${DFM_SECRET_KEY}
      ALLOWED_IPS: ${DFM_ALLOWED_IPS}
    develop:
      watch:
        - action: rebuild
          path: ./server/src
    stop_grace_period: ${DFM_DEV_GRACE_PERIOD:-5s}
    restart: unless-stopped

  migrator:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command:
      - "-path=/migrations/"
      - "-database=postgres://${DFM_POSTGRES_USER:-dfuser}:${DFM_POSTGRES_PASSWORD}@postgres:5432/${DFM_POSTGRES_DB:-dfmailbox}?sslmode=disable"
      - "up"
    depends_on:
      - postgres
    restart: "no"

volumes:
  postgres_data:

