name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.11.0-rc1"
          rebar3-version: "3"
          elixir-version: "1"

      - name: Download deps
        working-directory: ./server/
        run: gleam deps download
      - name: Run tests
        working-directory: ./server/
        run: gleam test
      - name: Formatting check
        working-directory: ./server/
        run: gleam format --check src test
